---
title: "shrek"
author: "Kimberly Zhang, Emily Raphael, Maddie Haines"
date: "12/1/2017"
output: html_document
code_folding: hide 
---

```{r Load Library, message=FALSE, warning=FALSE}
library(mdsr)
library(RMySQL)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(RColorBrewer)
library(stringr)
library(devtools)
library(rvest)
library(plotly)
library(gapminder)
library(ggthemes)
db <- dbConnect_scidb(db = "imdb")

#devtools::install_github("benmarwick/wordcountaddin", 
                      #type = "source", dependencies = TRUE)

#wordcountaddin:::text_stats("shrek")
```


```{r Query Data, message=FALSE, warning=FALSE}
genres <- db %>%
  dbGetQuery("select t.id , t.title, mi.info, t.production_year
from title t 
inner join imdb.movie_info mi on mi.movie_id = t.id
  #joined to find a genre label for each movie
where info_type_id = '3' 
and t.kind_id = '1'")
#filtered to only show data for genres in movies

sequels <- db %>% 
  dbGetQuery("select  t.id, t.title, t.production_year, mii.info AS ratings, lt.link, mv.movie_id, mv.linked_movie_id
from title t 
inner join movie_link mv on mv.linked_movie_id = t.id
  #joined movie link to title to get how each movie is connected to other movies
left join link_type lt on lt.id = mv.link_type_id 
  #joined the link type to the movie link table to get the descriptions of how each movie is connected
left join movie_info_idx mii on mii.movie_id = t.id 
  #joined movie id to movie info to get ratings of each movie
where t.kind_id = '1' and
mii.info_type_id = 101 and 
lt.link like 'follow%' or 'rema%' or 'version%' and mii.info = 'Animation';")
  #filtered for only movies, ratings and the specific links that will tell us about sequels

shrek <- db %>%
  dbGetQuery("select t.id , t.title, mi.info, mii.info AS ratings, t.production_year
from title t 
inner join imdb.movie_info mi on mi.movie_id = t.id
left join movie_info_idx mii on mii.movie_id = t.id 
  #joined to find a genre label for each movie
where mi.info_type_id = '3' and mii.info_type_id = 101 and mi.info = 'Animation' and t.title like '%shrek%'")

moneys <- db %>%
  dbGetQuery("select t.id, t.title, t.production_year, mii.info AS budget, mii2.info AS gross
from title t
join movie_info mii ON mii.movie_id = t.id
join movie_info mii2 ON mii2.movie_id = t.id
where t.kind_id = 1
  and mii.info_type_id = 105
  and mii2.info_type_id = 107
  and mii2.info like '%USA%';")

animation <- db %>%
  dbGetQuery("select t.id , t.title, mi.info, mii.info AS ratings, t.production_year
from title t 
inner join imdb.movie_info mi on mi.movie_id = t.id
left join movie_info_idx mii on mii.movie_id = t.id 
  #joined to find a genre label for each movie
where mi.info_type_id = '3' and mii.info_type_id = 101 and mi.info = 'Animation' and production_year > '1995'")
```


```{r Shrek Table, message=FALSE, warning= FALSE}
#input shrek data
url <- "http://www.boxofficemojo.com/franchises/chart/?id=shrek.htm"

html_bom <- read_html(url)
class(html)
html_bom

tables <- html_bom %>%
  html_nodes("table")

shrekmovies <- tables[[6]] %>%
  html_table(header = TRUE)

#shrek movies already adjusted for inflation

shrekmovies <- shrekmovies %>%
  head(n = 5)
#create base shrek table
require(lubridate)
grosshrek <- shrekmovies %>%
  mutate(date = mdy(Release), 
         gross = parse_number(`Adjusted Gross`)) %>%
  rename(title = "Title (click to view)") %>%
  select(title, gross, date)
```

```{r Despicable Me Table, message=FALSE, warning=FALSE}
#input Despicable Me Data

url <- "http://www.boxofficemojo.com/franchises/chart/?id=despicableme.htm"

html_bom <- read_html(url)
class(html)

tables <- html_bom %>%
  html_nodes("table")
#Already Adjusted for Inflation

DE <- tables[[6]] %>%
  html_table(header = TRUE) %>%
  head(4)
#create Despicable me table
require(lubridate)
DE <- DE %>%
  mutate(gross = parse_number(`Adjusted Gross`), date = mdy(Release), avg = sum(gross)/n()) %>%
  rename(title = "Title (click to view)") %>%
  select(title, gross, date, avg) 

```

```{r Toy Story Table, message=FALSE, warning=FALSE}
#input Toy Story Data
urltoystory <- "http://www.boxofficemojo.com/franchises/chart/?view=main&id=toystory.htm&p=.htm"

html_bom <- read_html(urltoystory)
class(html)
#Already Adjusted for Inflation
tablest <- html_bom %>%
  html_nodes("table")

andy <- tablest[[6]] %>%
  html_table(header = TRUE)
#Create basic Toy Story Table
 toystory <- andy %>%
  head(3) %>%
  mutate(gross = parse_number(`Adjusted Gross`), date = mdy(Release), avg = sum(gross)/n()) %>%
  rename(title = "Title (click to view)") %>%
  select(title, gross, date, avg)
```

```{r Ice Age Tabel , message=FALSE, warning=FALSE}
#input Ice Age Table
url <- "http://www.boxofficemojo.com/franchises/chart/?id=iceage.htm"

html_bom <- read_html(url)
class(html)
#Already Adjusted For Inflation
tables <- html_bom %>%
  html_nodes("table")

mammoth <- tables[[6]] %>%
  html_table(header = TRUE)
#Create basic Ice Age Table
iceage <- mammoth %>%
  head(5) %>%
  mutate(gross = parse_number(`Adjusted Gross`), date = mdy(Release), avg = sum(gross)/n()) %>%
  rename(title = "Title (click to view)") %>%
  select(title, gross, date, avg)

```

```{r Average Animation Table, message=FALSE, warning=FALSE}
#Create Basic Animated movies table
animationmoney <- inner_join(animation, moneys, by = "id")

animationmoney %>%
  mutate(revenue = unlist(str_split(gross, pattern = "\\(", n = 1)))

animationmoney$revenue <- str_split_fixed(animationmoney$gross, pattern = "\\(", n = 3) [ , 1] %>% 
  parse_number()

animationseq <- left_join(animationmoney, sequels, by = 'id')

#Mutate table to find animated movie gross average per year
average_anim <- animationseq %>%
  group_by(title.x, id) %>%
  mutate(actualrev = max(revenue))%>%
  ungroup(title.x, id) %>%
  #Needs to be a date to go on the same graph as the movie points
  mutate(year = as.Date(paste0(production_year.x, '-01-01'))) %>%
  group_by(year) %>%
  mutate(avg = sum(actualrev)/n()) %>%
  arrange(desc(actualrev)) %>%
  distinct(id, .keep_all = TRUE) %>%
  select(id, title.x, actualrev, avg, production_year)%>%
  #2017 Skews the data
  filter(year != "2017-01-01")

```

```{r Animated Comparison Graph, message=FALSE, warning=FALSE}
#Manually creates the legend
legend <- c( "Toy Story" = "#AF1B3F", "Despicable Me" = "#EAC435", "Shrek" = "#0B5D1E","Ice Age"= "#197278", "Average" ="#686868" )
#Graphic that compares top animated films compared to the average gross, using tables created in previous r chunks
compare <-
  ggplot(data = grosshrek, aes(x = date, y = gross, text = title, text2 = date, text3 = gross, colour = gross)) + 
  #average line
  geom_line(data = average_anim, aes(x = year, y = avg, color = "Average"), alpha = 0.6, inherit.aes = FALSE) +
  #Shrek data
  geom_point(size = 4, aes(color = "Shrek")) +
  #Despicable me data
  geom_point(data = DE, aes(x = date, y = gross, text = title, text2 = date, text3 = gross, color = "Despicable Me"), size = 4, inherit.aes = FALSE)+
  #Ice Age data
  geom_point(data = iceage, aes(x = date, y = gross, color = "Ice Age",text = title, text2 = date, text3 = gross), size = 4, inherit.aes = FALSE)+
  #Toy Story Data
  geom_point(data = toystory, aes(x = date, y = gross, text = title, text2 = date, text3 = gross, color = "Toy Story"), size = 4, inherit.aes = FALSE)+
  #manually creates legend
  scale_color_manual( values = legend)+
  ggtitle( "Animated Movies")+
  scale_y_continuous(limit = c(0,700000000), 
                     breaks = c(0,200000000,400000000,600000000), 
                     labels = c("$0","$200M", "$400M","$600M")) +
  labs( x = "Release Date", y = "Total Gross", face = "bold") +
   theme_fivethirtyeight() +
   theme(axis.title.y = element_text("Total Gross", size = (14)), 
        axis.title.x = element_text("Release Date", size = (14)), 
        axis.text = element_text(size = (10)), 
        legend.title= element_blank())

#tooltip animation
compare <- ggplotly(tooltip = c("text", "text2", "text3"))
compare

```

```{r Myers Tables, message=FALSE, warning=FALSE}
#input Myers Movie Data
url <- "http://www.boxofficemojo.com/people/chart/?view=Actor&id=mikemyers.htm&sort=date&order=ASC&p=.htm"

html_bom <- read_html(url)
tables <- html_bom %>%
  html_nodes("table")
myers_movies <- tables[[3]] %>%
  html_table(header = TRUE)
glimpse(myers_movies)

require(lubridate)
myers_movies <- myers_movies[,-7]
#Main myers table
myers_movies <- myers_movies %>%
  mutate(date = mdy(Date),
         opening = parse_number(`Opening / Theaters`),
         lifetime = parse_number(`Lifetime Gross / Theaters`))%>%
  rename( Title = `Title (click to view)`)
myers_movies <- myers_movies %>% 
  rename(LifetimeGross = `Lifetime Gross / Theaters`)

#Myers movies that are not shrek
noshrek <- myers_movies %>% 
  filter(!Title %in% c("Shrek(Voice)","Shrek 2(Voice)","Shrek the Third(Voice)","Shrek Forever After(Voice)"))
```

```{r Shrek Movies, message=FALSE, warning=FALSE}
#just shrek movies table 
justshrek <- myers_movies %>% 
 filter(Title %in% c("Shrek(Voice)", "Shrek 2(Voice)", "Shrek the Third(Voice)", "Shrek Forever After(Voice)"))

```

```{r Myers Movies Graphic, message=FALSE, warning=FALSE}

myerz <-ggplot(data = myers_movies, aes(x = date, y = lifetime, text = paste(Title), text2 = Date,text3 = LifetimeGross)) + 
  #Shrek data
  geom_point(data = justshrek, aes(x = date, y = lifetime, text = Title, text2 = Date,text3 = LifetimeGross,size = lifetime),color = "#0B5D1E", inherit.aes = FALSE) +
  #Myers movie data (no shrek)
  geom_point(data = noshrek, aes(x = date, y = lifetime, text = Title, text2 = Date,text3 = LifetimeGross,size = lifetime), alpha = 0.8,color = "#686868", inherit.aes = FALSE) +
  scale_y_continuous(limit = c(0,500000000), 
                     breaks = c(0,100000000,200000000,300000000,400000000), 
                     labels = c("$0","$100M", "$200M", "$300M", "$400M")) +
  labs( x = "Release Date", y = "Total Gross") +
  ggtitle("Mike Myer's Movies")+ 
  theme_fivethirtyeight()+
   theme(axis.title.y = element_text("Total Gross", size = (14), face = "bold"), 
        axis.title.x = element_text("Release Date", size = (14), face = "bold"), 
        axis.text = element_text( size = (10)))
#tooltip animation
myers <- ggplotly(tooltip = c("text", "text2", "text3"))
myers

```

```{r Diaz Tables, message=FALSE, warning=FALSE}
#input Diaz Movie Data
url <- "http://www.boxofficemojo.com/people/chart/?id=camerondiaz.htm"
html_bom <- read_html(url)
tables <- html_bom %>%
  html_nodes("table")
diaz_movies <- tables[[3]] %>%
  html_table(header = TRUE)

require(lubridate)
diaz_movies <- diaz_movies[,-7]

#Main Diaz movie table
diaz_movies <- diaz_movies %>%
  mutate(date = mdy(Date),
         opening = parse_number(`Opening / Theaters`),
         lifetime = parse_number(`Lifetime Gross / Theaters`))%>%
 rename( Title = `Title (click to view)`)
diaz_movies <- diaz_movies %>% 
  rename(LifetimeGross = `Lifetime Gross / Theaters`)

#Diaz movies that aren't shrek
noshrek2 <- diaz_movies %>% 
  filter(!Title %in% c("Shrek(Voice)","Shrek 2(Voice)","Shrek the Third(Voice)","Shrek Forever After(Voice)"))

```

```{r Diaz Movie Graphic, message=FALSE, warning=FALSE}

diazz <-ggplot(data = diaz_movies, aes(x = date, y = lifetime, text = paste(Title), text2 = Date,text3 = LifetimeGross)) +
  #Shrek data
  geom_point(data = justshrek, aes(x = date, y = lifetime, text = Title, text2 = Date,text3 = LifetimeGross,size = lifetime),color = "#0B5D1E", inherit.aes = FALSE) +
  #Myers movie data (no shrek)
  geom_point(data = noshrek2, aes(x = date, y = lifetime, text = Title, text2 = Date,text3 = LifetimeGross,size = lifetime), alpha = 0.8,color = "#686868", inherit.aes = FALSE) +
  scale_y_continuous(limit = c(0,500000000), 
                     breaks = c(0,100000000,200000000,300000000,400000000), 
                     labels = c("$0","$100M", "$200M", "$300M", "$400M")) +
  labs( x = "Release Date", y = "Total Gross") +
  ggtitle("Cameron Diaz's Movies")+ 
  theme_fivethirtyeight()+
   theme(axis.title.y = element_text("Total Gross", size = (14)), 
        axis.title.x = element_text("Release Date", size = (14)), 
        axis.text = element_text( size = (10)))
#tooltip animation
diazz <- ggplotly(tooltip = c("text", "text2", "text3"))
diazz

```


```{r Murphy Movie Table, message=FALSE, warning=FALSE}
#input Murphy Data
url <- "http://www.boxofficemojo.com/people/chart/?id=eddiemurphy.htm"

html_bom <- read_html(url)
tables <- html_bom %>%
  html_nodes("table")
murphy_movies <- tables[[3]] %>%
  html_table(header = TRUE)

require(lubridate)
murphy_movies <- murphy_movies[,-7]
#Main murphy table
murphy_movies <- murphy_movies %>%
  mutate(date = mdy(Date),
         opening = parse_number(`Opening / Theaters`),
         lifetime = parse_number(`Lifetime Gross / Theaters`))%>%
 rename( Title = `Title (click to view)`)
murphy_movies <- murphy_movies %>% 
  rename(LifetimeGross = `Lifetime Gross / Theaters`)

#Murphy movies w/o shrek
noshrek3 <- murphy_movies %>% 
  filter(!Title %in% c("Shrek(Voice)","Shrek 2(Voice)","Shrek the Third(Voice)","Shrek Forever After(Voice)"))

```

```{r Murphy Movie Graphic, message=FALSE, warning=FALSE}

murphy <-ggplot(data = murphy_movies, aes(x = date, y = lifetime, text = paste(Title), text2 = Date,text3 = LifetimeGross)) + 
  #Shrek data
  geom_point(data = justshrek, aes(x = date, y = lifetime, text = Title, text2 = Date,text3 = LifetimeGross,size = lifetime),color = "#0B5D1E", inherit.aes = FALSE) +
  #Murphy movies (no shrek)
  geom_point(data = noshrek3, aes(x = date, y = lifetime, text = Title, text2 = Date,text3 = LifetimeGross,size = lifetime), alpha = 0.8,color = "#686868", inherit.aes = FALSE) +
  scale_y_continuous(limit = c(0,500000000), 
                     breaks = c(0,100000000,200000000,300000000,400000000), 
                     labels = c("$0","$100M", "$200M", "$300M", "$400M")) +
  labs( x = "Release Date", y = "Total Gross") +
  ggtitle("Eddie Murphy's Movies")+ 
  theme_fivethirtyeight()+
   theme(axis.title.y = element_text("Total Gross", size = (14)), 
        axis.title.x = element_text("Release Date", size = (14)), 
        axis.text = element_text( size = (10)))

murphy <- ggplotly(tooltip = c("text", "text2", "text3"))
murphy
```



**GitHub**
https://github.com/kimbrlyzhang/miniproject4 

